// Plain kebab-case slug for the SEO taxonomy's URL hierarchy — identical
// algorithm to the frontend's lib/slug.js (Step 3/4 of the SEO
// restructuring project). Kept in sync by hand across the two repos, same
// convention as scripts/backfillVendorPlaceIds.js mirroring
// place.controller.js's matching logic — this MUST stay byte-for-byte
// identical, or a state/city slug generated by one side won't resolve on
// the other.
function slugify(name) {
  return name.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

module.exports = { slugify };
